import './../envConfig'
import "@/app/globals.css";
import SideBarMA from "@/app/sidebar";
import HeadSEO from "./head";
import Footer from "./footer";
import { Toaster } from "@/components/ui/sonner"
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <HeadSEO title="System" description="System description" ogImage={"ogimage.png"} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <SideBarMA>
            {children}
          </SideBarMA>
        </div>
        <Toaster richColors />
        <Footer>
        </Footer>
      </body>
    </html>
  )
}